### Step 1: Check numply library

In [ ]:
pip show numpy

### Step 2: install numpy

In [ ]:
pip install numpy

### Step 3: Create Array

In [9]:
import numpy as np

# Scalar Array
a = np.array(10)
print(a)

# Vector Array
row = np.array([1, 2, 3]) # 1 row and 3 columns
col = np.array([[1],[2],[3]]) # 3 rows and 1 column
print(row)
print(col)

# Matrix Array
mat = np.array([[10, 11, 12],[13, 14, 15]]) # 2 rows and 3 columns
print(mat)

10
[1 2 3]
[[1]
 [2]
 [3]]
[[10 11 12]
 [13 14 15]]


### Step 4: Create random number

In [13]:
# Random 0-1
r1 = np.random.random(4) # random vector 4 value
r2 = np.random.random((2, 3)) # random maxtrix 2x3
print(r1)
print(r2)

# Random positive integer
r3 = np.random.randint(0, 11, 6) # random 3 value from 0-10
r4 = np.random.randint(0, 11, [2, 3]) # random maxtrix 2x3 from 0-10
print(r3)
print(r4)

[0.20578864 0.37067101 0.81207636 0.59775123]
[[0.48800067 0.67387717 0.3211565 ]
 [0.50740654 0.50696702 0.97032606]]
[8 9 2 1 9 3]
[[ 3 10  0]
 [ 4  2  7]]


### Step 5: read index array

In [20]:
vrow = np.array([1,2,3,4,5,6,7,8,9,10])

print(vrow[3]) # read from front
print(vrow[-1]) # read from back
print(vrow[-1]) # read from back
print(vrow[2:7]) # read from 2 to 6
print(vrow[:4]) # read from 0 to 3
print(vrow[4:]) # read from 5 to end

4
10
10
[3 4 5 6 7]
[1 2 3 4]
[ 5  6  7  8  9 10]


### Step 6: ການຫາຄ່າສະຖິຕິຂອງຂໍ້ມູນດ້ວຍ numpy

In [29]:
stat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(stat)

# Max number
print("Max: ", np.max(stat))
# min number
print("Min: ", np.min(stat))
# Average number
print("Mean: ", np.mean(stat))
# Median number
print("Median: ", np.median(stat))
# Std number (ຄ່າຜັນປ່ຽນມາຕະຖານ)
print("Std: ", np.std(stat))
# var number (ຄ່າຄວາມປ່ຽນແປງ)
print("Var: ", np.var(stat))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Max:  12
Min:  1
Mean:  6.5
Median:  6.5
Std:  3.452052529534663
Var:  11.916666666666666
